# Generated by Django 2.1.3 on 2018-11-27 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('completion_state', models.IntegerField(default=0)),
                ('date_created', models.DateField(verbose_name='date created')),
                ('time_scheduled', models.IntegerField(default=-1)),
                ('time_length', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slot_size', models.IntegerField(default=30)),
                ('start_day', models.IntegerField(default=8)),
                ('end_day', models.IntegerField(default=22)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='todolist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktracker.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='to_do_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktracker.ToDoList'),
        ),
    ]
